local config = require("vimoire.config")
local editor = config.get("editor")

vim.o.confirm = true
vim.o.cursorline = false
vim.o.expandtab = false
vim.o.ignorecase = true
vim.o.linebreak = editor.linebreak
vim.o.mouse = "a"
vim.o.number = false
vim.o.scrolloff = editor.scrolloff
vim.o.shiftwidth = editor.shiftwidth
vim.o.smartcase = true
vim.o.tabstop = editor.tabstop
vim.o.textwidth = editor.textwidth
vim.o.swapfile = false
vim.o.undofile = true
vim.o.wildignore = ".git,*.swp,*.tmp"
vim.o.wrap = editor.wrap
vim.o.termguicolors = editor.termguicolors
