vim.o.confirm = true
vim.o.cursorline = false
vim.o.expandtab = false
vim.o.ignorecase = true
vim.o.linebreak = true
vim.o.mouse = "a"
vim.o.number = false
vim.o.scrolloff = 5
vim.o.shiftwidth = 4
vim.o.showbreak = "↳ "
vim.o.smartcase = true
vim.o.tabstop = 4
vim.o.textwidth = 80
vim.o.undofile = true
vim.o.wildignore = ".git,*.swp,*.tmp"
vim.o.wrap = true
