#!/bin/bash
DIR="$(cd "$(dirname "$0")/.." && pwd)"

# TODO: Uncomment --icon once neovide stable includes it (after 0.15.2)
# Requires: https://github.com/neovide/neovide/pull/3272
NVIM_APPNAME=vimoire /opt/homebrew/bin/neovide "$@"
# NVIM_APPNAME=vimoire /opt/homebrew/bin/neovide --icon "$DIR/Resources/vimoire.icns" "$@"
